### PR TITLE
Moved glossary.

### PR DESCRIPTION
**Pull request by m-mohr**

### CODE REVIEW

**Comment by edzer** [comment]
It seems this removes the glossary and replaces it with (a link to) the docs. I think it is a good idea to add the docs, but the glossary should remain linked from the opening page. (The duplication with the glossary repo needs to be removed, though).

**Comment by m-mohr** [comment]
Okay, I'll change that...

**Comment by m-mohr** [comment]
@edzer Is this how you expect it to be?

**Comment by edzer** [comment]
Yes, thanks!

**Pull request merged**
